CREATE TABLE CORPORATIVO.UTA
(
    ID_UTA       NUMBER                                               NOT NULL,
    NOME         VARCHAR2(100)                                        NOT NULL,
    DESCRICAO    VARCHAR2(1000),
    IS_ATIVO     CHAR(1) DEFAULT 'S' CHECK ( IS_ATIVO IN ('S', 'N') ) NOT NULL,
    DATA_CRIACAO DATE    DEFAULT SYSDATE,
    DATA_FIM     DATE,
    ID_UTA_PAI   NUMBER,
    PRIMARY KEY (ID_UTA),
    CONSTRAINT FK_UTA_PAI FOREIGN KEY (ID_UTA_PAI) REFERENCES UTA (ID_UTA)
);
CREATE SEQUENCE CORPORATIVO.SEQ_UTA START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CORPORATIVO.PESSOA_FISICA
(
    ID_PESSOA_FISICA NUMBER                                                    NOT NULL,
    NOME             VARCHAR2(80)                                              NOT NULL,
    CPF              VARCHAR2(11) UNIQUE                                       NOT NULL,
    RG               VARCHAR2(15),
    DATA_NASCIMENTO  DATE,
    EMAIL            VARCHAR2(100) UNIQUE,
    TELEFONE         VARCHAR2(15),
    ENDERECO         VARCHAR2(255),
    CIDADE           VARCHAR2(50),
    ESTADO           VARCHAR2(2),
    CEP              VARCHAR2(8),
    NACIONALIDADE    VARCHAR2(50) DEFAULT 'Brasileiro',
    ESTADO_CIVIL     VARCHAR2(20),
    GENERO           VARCHAR2(10) CHECK (GENERO IN ('Masculino', 'Feminino', 'Outro')),
    IS_ATIVO         CHAR(1)      DEFAULT 'S' CHECK ( IS_ATIVO IN ('S', 'N') ) NOT NULL,
    DATA_CRIACAO     DATE         DEFAULT SYSDATE                              NOT NULL,
    PRIMARY KEY (ID_PESSOA_FISICA)
);
CREATE SEQUENCE CORPORATIVO.SEQ_PESSOA_FISICA START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CORPORATIVO.FUNCIONARIO
(
    ID_FUNCIONARIO    NUMBER                                               NOT NULL,
    ID_PESSOA_FISICA  NUMBER                                               NOT NULL,
    CARGO             VARCHAR2(100)                                        NOT NULL,
    DATA_ADMISSAO     DATE    DEFAULT SYSDATE                              NOT NULL,
    DATA_DESLIGAMENTO DATE,
    ID_UTA            NUMBER                                               NOT NULL,
    IS_ATIVO          CHAR(1) DEFAULT 'S' CHECK ( IS_ATIVO IN ('S', 'N') ) NOT NULL,
    PRIMARY KEY (ID_FUNCIONARIO),
    CONSTRAINT FK_FUNCIONARIO_PF FOREIGN KEY (ID_PESSOA_FISICA) REFERENCES CORPORATIVO.PESSOA_FISICA (ID_PESSOA_FISICA),
    CONSTRAINT FK_FUNCIONARIO_ID_UTA FOREIGN KEY (ID_UTA) REFERENCES UTA (ID_UTA)
);
CREATE SEQUENCE CORPORATIVO.SEQ_FUNCIONARIO START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CORPORATIVO.LOGIN
(
    ID_LOGIN       NUMBER              NOT NULL,
    LOGIN          VARCHAR2(25) UNIQUE NOT NULL,
    SENHA          VARCHAR2(2000)      NOT NULL,
    DATA_CADASTRO  DATE DEFAULT SYSDATE,
    DATA_EXPIRACAO DATE,
    ID_FUNCIONARIO NUMBER              NOT NULL,
    PRIMARY KEY (ID_LOGIN),
    CONSTRAINT FK_LOGIN_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES CORPORATIVO.FUNCIONARIO (ID_FUNCIONARIO)
);
CREATE SEQUENCE CORPORATIVO.SEQ_LOGIN START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CORPORATIVO.DOMINIO
(
    ID_DOMINIO NUMBER                                               NOT NULL,
    NOME       VARCHAR2(60)                                         NOT NULL,
    DESCRICAO  VARCHAR2(4000)                                       NOT NULL,
    IS_ATIVO   CHAR(1) DEFAULT 'S' CHECK ( IS_ATIVO IN ('S', 'N') ) NOT NULL,
    PRIMARY KEY (ID_DOMINIO)
);
CREATE SEQUENCE CORPORATIVO.SEQ_CORPORATIVO START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CORPORATIVO.PAPEL
(
    ID_PAPEL  NUMBER                                               NOT NULL,
    NOME      VARCHAR2(60)                                         NOT NULL,
    DESCRICAO VARCHAR2(4000)                                       NOT NULL,
    IS_ATIVO  CHAR(1) DEFAULT 'S' CHECK ( IS_ATIVO IN ('S', 'N') ) NOT NULL,
    PRIMARY KEY (ID_PAPEL)
);
CREATE SEQUENCE CORPORATIVO.SEQ_PAPEL START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CORPORATIVO.GESTORES
(
    ID_GESTORES      NUMBER               NOT NULL,
    ID_PESSOA_FISICA NUMBER               NOT NULL,
    ID_DOMINIO       NUMBER,
    ID_PAPEL         NUMBER,
    DATA_INICIO      DATE DEFAULT SYSDATE NOT NULL,
    DATA_FIM         DATE,
    PRIMARY KEY (ID_GESTORES),
    CONSTRAINT FK_GESTORES_ID_DOMINIO FOREIGN KEY (ID_DOMINIO) REFERENCES CORPORATIVO.DOMINIO (ID_DOMINIO),
    CONSTRAINT FK_GESTORES_ID_PAPEL FOREIGN KEY (ID_PAPEL) REFERENCES CORPORATIVO.PAPEL (ID_PAPEL),
    CONSTRAINT FK_GESTORES_ID_PESSOA_FISICA FOREIGN KEY (ID_PESSOA_FISICA) REFERENCES CORPORATIVO.PESSOA_FISICA (ID_PESSOA_FISICA)
);
CREATE SEQUENCE CORPORATIVO.SEQ_GESTORES START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CORPORATIVO.ACAO
(
    ID_ACAO   NUMBER                                               NOT NULL,
    NOME      VARCHAR2(60)                                         NOT NULL,
    DESCRICAO VARCHAR2(4000)                                       NOT NULL,
    IS_ATIVO  CHAR(1) DEFAULT 'S' CHECK ( IS_ATIVO IN ('S', 'N') ) NOT NULL,
    PRIMARY KEY (ID_ACAO)
);
CREATE SEQUENCE CORPORATIVO.SEQ_ACAO START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CORPORATIVO.PAPEIS_HABILITADOS_ACAO
(
    ID_PAPEIS_HABILITADOS_ACAO NUMBER NOT NULL,
    ID_PAPEL                   NUMBER NOT NULL,
    ID_ACAO                    NUMBER NOT NULL,
    PRIMARY KEY (ID_PAPEIS_HABILITADOS_ACAO),
    CONSTRAINT FK_PAPEIS_HABILITADOS_ACAO_ID_PAPEL FOREIGN KEY (ID_PAPEL) REFERENCES CORPORATIVO.PAPEL (ID_PAPEL),
    CONSTRAINT FK_PAPEIS_HABILITADOS_ACAO_ID_ACAO FOREIGN KEY (ID_ACAO) REFERENCES CORPORATIVO.ACAO (ID_ACAO)
);
CREATE SEQUENCE CORPORATIVO.SEQ_PAPEIS_HABILITADOS_ACAO START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CORPORATIVO.AUTORIZACOES
(
    ID_AUTORIZACOES  NUMBER NOT NULL,
    ID_PAPEL         NUMBER NOT NULL,
    ID_DOMINIO       NUMBER NOT NULL,
    ID_PESSOA_FISICA NUMBER NOT NULL,
    PRIMARY KEY (ID_AUTORIZACOES),
    CONSTRAINT FK_AUTORIZACOES_ID_PAPEL FOREIGN KEY (ID_PAPEL) REFERENCES CORPORATIVO.PAPEL (ID_PAPEL),
    CONSTRAINT FK_AUTORIZACOES_ID_DOMINIO FOREIGN KEY (ID_DOMINIO) REFERENCES CORPORATIVO.DOMINIO (ID_DOMINIO),
    CONSTRAINT FK_AUTORIZACOES_ID_PESSOA_FISICA FOREIGN KEY (ID_PESSOA_FISICA) REFERENCES CORPORATIVO.PESSOA_FISICA (ID_PESSOA_FISICA)
);
CREATE SEQUENCE CORPORATIVO.SEQ_AUTORIZACOES START WITH 1 INCREMENT BY 1 MINVALUE 1;


